### ISSUE TITLE
Call tokenize only once

### ISSUE THREAD

**Issue by astrojuanlu** [pedrolousantos/ie-titanic-utils#1]
In this code:

https://github.com/pedrolousantos/ie-titanic-utils/blob/ee03709d662726cc434f64e36c9c0862118c17ab/src/ie_utils/__main__.py#L6-L7

you're calling `tokenize` once per word, but instead you should call it once per sentence.

**Comment by pedrolousantos** [comment]
Thanks professor,

If I do:

"def main():
    print(tokenize(sys.argv))"

I get the error: AttributeError: 'list' object has no attribute 'split'.

So I should I overcome this?

Best regards,
Pedro

**Comment by astrojuanlu** [comment]
Oh right, because `sys.argv` is a list of strings, but you want to pass a single string. Therefore, you can do `tokenize(sys.argv[1])`, and then `ie_tokenize "Hello world!"` (note the quotes) will work.

**Comment by pedrolousantos** [comment]
It worked! Thanks professor! :)
